class Municipalities {
  Map _districtsAndMunicipalities = {
    "TAPLEJUNG": [
      "Sidingba",
      "Meringden",
      "Maiwakhola",
      "Phaktanglung",
      "Sirijangha",
      "Mikwakhola",
      "Aathrai Tribeni",
      "Pathivara Yangwarak",
      "Phungling "
    ],
    "SANKHUWASABHA": [
      "Makalu",
      "Chichila",
      "Silichong",
      "Bhotkhola",
      "Sabhapokhari",
      "Dharmadevi",
      "Madi",
      "Panchakhapan",
      "Chainpur",
      "Khandbari "
    ],
    "SOLUKHUMBU": [
      "Sotang",
      "Mahakulung",
      "Likhupike",
      "Nechasalyan",
      "Thulung Dudhkoshi",
      "Maapya Dudhkoshi",
      "Khumbupasanglahmu",
      "Solududhakunda "
    ],
    "OKHALDHUNGA": [
      "Likhu",
      "Molung",
      "Sunkoshi",
      "Champadevi",
      "Chisankhugadhi",
      "Khijidemba",
      "Manebhanjyang",
      "Siddhicharan "
    ],
    "KHOTANG": [
      "Sakela",
      "Khotehang",
      "Barahapokhari",
      "Ainselukhark",
      "Rawa Besi",
      "Kepilasagadhi",
      "Jantedhunga",
      "Diprung Chuichumma",
      "Halesi Tuwachung",
      "Diktel Rupakot Majhuwagadhi "
    ],
    "BHOJPUR": [
      "Arun",
      "Aamchowk",
      "Hatuwagadhi",
      "Pauwadungma",
      "Temkemaiyung",
      "Salpasilichho",
      "Ramprasad Rai",
      "Shadananda",
      "Bhojpur "
    ],
    "DHANKUTA": [
      "Chaubise",
      "Shahidbhumi",
      "Sangurigadhi",
      "Chhathar Jorpati",
      "Pakhribas",
      "Mahalaxmi",
      "Dhankuta "
    ],
    "TERHATHUM": [
      "Chhathar",
      "Phedap",
      "Aathrai",
      "Menchayam",
      "Laligurans",
      "Myanglung "
    ],
    "PANCHTHAR": [
      "Yangwarak",
      "Hilihang",
      "Falelung",
      "Tumbewa",
      "Kummayak",
      "Miklajung",
      "Falgunanda",
      "Phidim "
    ],
    "ILAM": [
      "Rong",
      "Mangsebung",
      "Chulachuli",
      "Sandakpur",
      "Fakphokthum",
      "Maijogmai",
      "Illam",
      "Mai",
      "Deumai",
      "Suryodaya "
    ],
    "JHAPA": [
      "Kamal",
      "Jhapa",
      "Kachankawal",
      "Gauriganj",
      "Barhadashi",
      "Haldibari",
      "Buddhashanti",
      "Shivasataxi",
      "Bhadrapur",
      "Kankai",
      "Birtamod",
      "Mechinagar",
      "Damak",
      "Arjundhara",
      "Gauradhaha "
    ],
    "MORANG": [
      "Jahada",
      "Katahari",
      "Gramthan",
      "Dhanpalthan",
      "Kerabari",
      "Budhiganga",
      "Kanepokhari",
      "Miklajung",
      "Letang",
      "Sunwarshi",
      "Rangeli",
      "Patahrishanishchare",
      "Biratnagar",
      "Uralabari",
      "Belbari",
      "Sundarharaicha",
      "Ratuwamai "
    ],
    "SUNSARI": [
      "Gadhi",
      "Koshi",
      "Barju",
      "Harinagar",
      "Dewanganj",
      "Bhokraha Narsing",
      "Ramdhuni",
      "Barahchhetra",
      "Duhabi",
      "Inaruwa",
      "Dharan",
      "Itahari "
    ],
    "UDAYAPUR": [
      "Tapli",
      "Rautamai",
      "Udayapurgadhi",
      "Limchungbung",
      "Chaudandigadhi",
      "Triyuga",
      "Katari",
      "Belaka "
    ],
    "SAPTARI": [
      "Rajgadh",
      "Rupani",
      "Tirahut",
      "Mahadeva",
      "Bishnupur",
      "Chhinnamasta",
      "Balan Bihul",
      "Tilathi Koiladi",
      "Agnisair Krishna Savaran",
      "Hanumannagar Kankalini",
      "Kanchanrup",
      "Rajbiraj",
      "Khadak",
      "Dakneshwori",
      "Saptakoshi",
      "Surunga",
      "Shambhunath",
      "Bode Barsain "
    ],
    "SIRAHA": [
      "Aurahi",
      "Naraha",
      "Arnama",
      "Bhagawanpur",
      "Nawarajpur",
      "Bishnupur",
      "Bariyarpatti",
      "Laxmipur Patari",
      "Sakhuwanankarkatti",
      "Mirchaiya",
      "Lahan",
      "Siraha",
      "Dhangadhimai",
      "Kalyanpur",
      "Karjanha",
      "Golbazar",
      "Sukhipur "
    ],
    "DHANUSA": [
      "Aaurahi",
      "Dhanauji",
      "Bateshwor",
      "Janaknandani",
      "Lakshminiya",
      "Mukhiyapatti Musarmiya",
      "Mithila Bihari",
      "Kamala",
      "Nagarain",
      "Ganeshman Charnath",
      "Mithila",
      "Dhanusadham",
      "Bideha",
      "Sabaila",
      "Hansapur",
      "Janakpurdham",
      "Sahidnagar",
      "Chhireshwornath "
    ],
    "MAHOTTARI": [
      "Pipra",
      "Sonama",
      "Samsi",
      "Ekdanra",
      "Mahottari",
      "Gaushala",
      "Ramgopalpur",
      "Aurahi",
      "Bardibas",
      "Bhangaha",
      "Jaleswor",
      "Balwa",
      "Manra Siswa",
      "Matihani",
      "Loharpatti "
    ],
    "SARLAHI": [
      "Dhankaul",
      "Parsa",
      "Bishnu",
      "Ramnagar",
      "Kaudena",
      "Basbariya",
      "Chandranagar",
      "Chakraghatta",
      "Bramhapuri",
      "Barahathawa",
      "Haripur",
      "Ishworpur",
      "Lalbandi",
      "Malangawa",
      "Kabilasi",
      "Bagmati",
      "Hariwan",
      "Balara",
      "Haripurwa",
      "Godaita "
    ],
    "RAUTAHAT": [
      "Yemunamai",
      "Durga Bhagwati",
      "Katahariya",
      "Maulapur",
      "Madhav Narayan",
      "Gaur",
      "Gujara",
      "Garuda",
      "Ishanath",
      "Chandrapur",
      "Dewahhi Gonahi",
      "Brindaban",
      "Rajpur",
      "Rajdevi",
      "Gadhimai",
      "Phatuwa Bijayapur",
      "Baudhimai",
      "Paroha "
    ],
    "BARA": [
      "Pheta",
      "Devtal",
      "Prasauni",
      "Suwarna",
      "Baragadhi",
      "Karaiyamai",
      "Parwanipur",
      "Bishrampur",
      "Adarshkotwal",
      "Jitpur Simara",
      "Kalaiya",
      "Pacharauta",
      "Nijgadh",
      "Simraungadh",
      "Mahagadhimai",
      "Kolhabi "
    ],
    "PARSA": [
      "Thori",
      "Dhobini",
      "Chhipaharmai",
      "Jirabhawani",
      "Jagarnathpur",
      "Kalikamai",
      "Bindabasini",
      "Pakahamainpur",
      "SakhuwaPrasauni",
      "Paterwasugauli",
      "Birgunj",
      "Bahudaramai",
      "Pokhariya",
      "Parsagadhi "
    ],
    "DOLAKHA": [
      "Bigu",
      "Sailung",
      "Melung",
      "Baiteshwor",
      "Tamakoshi",
      "Gaurishankar",
      "Kalinchok",
      "Jiri",
      "Bhimeshwor "
    ],
    "SINDHUPALCHOK": [
      "Jugal",
      "Balefi",
      "Sunkoshi",
      "Helambu",
      "Bhotekoshi",
      "Lisangkhu Pakhar",
      "Indrawati",
      "Tripurasundari",
      "Panchpokhari Thangpal",
      "Chautara SangachokGadhi",
      "Barhabise",
      "Melamchi "
    ],
    "RASUWA": [
      "Kalika",
      "Naukunda",
      "Uttargaya",
      "Gosaikunda",
      "Amachodingmo "
    ],
    "DHADING": [
      "Gajuri",
      "Galchi",
      "Thakre",
      "Siddhalek",
      "Khaniyabash",
      "Jwalamukhi",
      "Gangajamuna",
      "Rubi Valley",
      "Tripura Sundari",
      "Netrawati Dabjong",
      "Benighat Rorang",
      "Nilakantha",
      "Dhunibesi "
    ],
    "NUWAKOT": [
      "Kakani",
      "Tadi",
      "Likhu",
      "Myagang",
      "Shivapuri",
      "Kispang",
      "Suryagadhi",
      "Tarkeshwar",
      "Panchakanya",
      "Dupcheshwar",
      "Belkotgadhi",
      "Bidur "
    ],
    "KATHMANDU": [
      "Kirtipur",
      "Shankharapur",
      "Nagarjun",
      "Kageshwori Manahora",
      "Dakshinkali",
      "Budhanilakantha",
      "Tarakeshwor",
      "Kathmandu",
      "Tokha",
      "Chandragiri",
      "Gokarneshwor "
    ],
    "BHAKTAPUR": [
      "Changunarayan",
      "Suryabinayak",
      "Bhaktapur",
      "Madhyapur Thimi "
    ],
    "LALITPUR": [
      "Bagmati",
      "Mahankal",
      "Konjyosom",
      "Lalitpur",
      "Mahalaxmi",
      "Godawari "
    ],
    "KAVREPALANCHOK": [
      "Roshi",
      "Temal",
      "Bhumlu",
      "Mahabharat",
      "Bethanchowk",
      "Khanikhola",
      "Chaurideurali",
      "Banepa",
      "Mandandeupur",
      "Dhulikhel",
      "Panauti",
      "Namobuddha",
      "Panchkhal "
    ],
    "RAMECHHAP": [
      "Sunapati",
      "Doramba",
      "Umakunda",
      "Khadadevi",
      "Gokulganga",
      "Likhu Tamakoshi",
      "Manthali",
      "Ramechhap "
    ],
    "SINDHULI": [
      "Marin",
      "Phikkal",
      "Tinpatan",
      "Sunkoshi",
      "Golanjor",
      "Ghanglekh",
      "Hariharpurgadhi",
      "Dudhouli",
      "Kamalamai "
    ],
    "MAKWANPUR": [
      "Bakaiya",
      "Kailash",
      "Manahari",
      "Bhimphedi",
      "Bagmati",
      "Raksirang",
      "Makawanpurgadhi",
      "Indrasarowar",
      "Hetauda",
      "Thaha "
    ],
    "CHITAWAN": [
      "Ichchhyakamana",
      "Bharatpur",
      "Kalika",
      "Khairahani",
      "Madi",
      "Rapti",
      "Ratnanagar "
    ],
    "GORKHA": [
      "Gandaki",
      "Dharche",
      "Aarughat",
      "Ajirkot",
      "Sahid Lakhan",
      "Siranchok",
      "Bhimsenthapa",
      "Chum Nubri",
      "Barpak Sulikot",
      "Palungtar",
      "Gorkha "
    ],
    "MANANG": [
      "Chame",
      "Narshon",
      "Narpa Bhumi",
      "Manang Ingshyang ",
    ],
    "MUSTANG": [
      "Thasang",
      "Gharapjhong",
      "Lomanthang",
      "Lo-Ghekar Damodarkunda",
      "Waragung Muktikhsetra "
    ],
    "MYAGDI": [
      "Mangala",
      "Malika",
      "Raghuganga",
      "Dhaulagiri",
      "Annapurna",
      "Beni "
    ],
    "KASKI": [
      "Rupa",
      "Madi",
      "Annapurna",
      "Machhapuchchhre",
      "Pokhara",
    ],
    "LAMJUNG": [
      "Dordi",
      "Dudhpokhari",
      "Marsyangdi",
      "Kwholasothar",
      "Sundarbazar",
      "Besishahar",
      "Rainas",
      "MadhyaNepal "
    ],
    "TANAHU": [
      "Ghiring",
      "Devghat",
      "Rhishing",
      "Myagde",
      "Bandipur",
      "Anbukhaireni",
      "Byas",
      "Shuklagandaki",
      "Bhimad",
      "Bhanu "
    ],
    "NAWALPARASI EAST": [
      "Baudeekali",
      "Bulingtar",
      "Hupsekot",
      "Binayee Tribeni",
      "Madhyabindu",
      "Devchuli",
      "Gaidakot",
      "Kawasoti "
    ],
    "SYANGJA": [
      "Harinas",
      "Biruwa",
      "Aandhikhola",
      "Phedikhola",
      "Kaligandagi",
      "Arjunchaupari",
      "Putalibazar",
      "Bhirkot",
      "Galyang",
      "Chapakot",
      "Waling "
    ],
    "PARBAT": [
      "Modi",
      "Painyu",
      "Jaljala",
      "Bihadi",
      "Mahashila",
      "Kushma",
      "Phalebas "
    ],
    "BAGLUNG": [
      "Bareng",
      "Badigad",
      "Nisikhola",
      "Kanthekhola",
      "Tara Khola",
      "Taman Khola",
      "Jaimuni",
      "Baglung",
      "Galkot",
      "Dhorpatan "
    ],
    "RUKUM EAST": [
      "Bhume",
      "Sisne",
      "Putha Uttarganga ",
    ],
    "ROLPA": [
      "Madi",
      "Thawang",
      "Sunchhahari",
      "Lungri",
      "Gangadev",
      "Tribeni",
      "Pariwartan",
      "Runtigadi",
      "Sunil Smriti",
      "Rolpa "
    ],
    "PYUTHAN": [
      "Ayirabati",
      "Gaumukhi",
      "Jhimruk",
      "Naubahini",
      "Mandavi",
      "Mallarani",
      "Sarumarani",
      "Pyuthan",
      "Sworgadwary "
    ],
    "GULMI": [
      "Ruru",
      "Isma",
      "Madane",
      "Malika",
      "Chatrakot",
      "Dhurkot",
      "Satyawati",
      "Chandrakot",
      "Kaligandaki",
      "Gulmidarbar",
      "Resunga",
      "Musikot "
    ],
    "ARGHAKHANCHI": [
      "Panini",
      "Chhatradev",
      "Malarani",
      "Bhumekasthan",
      "Sitganga",
      "Sandhikharka "
    ],
    "PALPA": [
      "Rambha",
      "Tinau",
      "Nisdi",
      "Mathagadhi",
      "Ribdikot",
      "Purbakhola",
      "Bagnaskali",
      "Rainadevi Chhahara",
      "Tansen",
      "Rampur "
    ],
    "NAWALPARASI WEST": [
      "Sarawal",
      "Susta",
      "Pratappur",
      "Palhi Nandan",
      "Bardaghat",
      "Sunwal",
      "Ramgram "
    ],
    "RUPANDEHI": [
      "Kanchan",
      "Siyari",
      "Rohini",
      "Gaidahawa",
      "Omsatiya",
      "Sudhdhodhan",
      "Mayadevi",
      "Marchawari",
      "Kotahimai",
      "Sammarimai",
      "Butwal",
      "Lumbini Sanskritik",
      "Devdaha",
      "Sainamaina",
      "Siddharthanagar",
      "Tillotama "
    ],
    "KAPILBASTU": [
      "Yashodhara",
      "Bijayanagar",
      "Mayadevi",
      "Suddhodhan",
      "Shivaraj",
      "Kapilbastu",
      "Buddhabhumi",
      "Maharajgunj",
      "Banganga",
      "Krishnanagar "
    ],
    "DANG": [
      "Babai",
      "Gadhawa",
      "Rapti",
      "Rajpur",
      "Dangisharan",
      "Shantinagar",
      "Banglachuli",
      "Tulsipur",
      "Ghorahi",
      "Lamahi "
    ],
    "BANKE": [
      "Khajura",
      "Janki",
      "Baijanath",
      "Duduwa",
      "Narainapur",
      "Rapti Sonari",
      "Kohalpur",
      "Nepalgunj "
    ],
    "BARDIYA": [
      "Geruwa",
      "Badhaiyatal",
      "Thakurbaba",
      "Bansagadhi",
      "Barbardiya",
      "Rajapur",
      "Madhuwan",
      "Gulariya "
    ],
    "DOLPA": [
      "Kaike",
      "Jagadulla",
      "Mudkechula",
      "Dolpo Buddha",
      "Shey Phoksundo",
      "Chharka Tangsong",
      "Tripurasundari",
      "Thuli Bheri "
    ],
    "MUGU": [
      "Soru",
      "Khatyad",
      "Mugum Karmarong",
      "Chhayanath Rara ",
    ],
    "HUMLA": [
      "Simkot",
      "Namkha",
      "Chankheli",
      "Tanjakot",
      "Sarkegad",
      "Adanchuli",
      "Kharpunath "
    ],
    "JUMLA": [
      "Hima",
      "Tila",
      "Sinja",
      "Guthichaur",
      "Tatopani",
      "Patrasi",
      "Kanakasundari",
      "Chandannath "
    ],
    "KALIKOT": [
      "Mahawai",
      "Palata",
      "Naraharinath",
      "Pachaljharana",
      "Subha Kalika",
      "Sanni Tribeni",
      "Khandachakra",
      "Raskot",
      "Tilagufa "
    ],
    "DAILEKH": [
      "Bhairabi",
      "Mahabu",
      "Gurans",
      "Naumule",
      "Bhagawatimai",
      "Thantikandh",
      "Dungeshwor",
      "Aathabis",
      "Dullu",
      "Chamunda Bindrasaini",
      "Narayan "
    ],
    "JAJARKOT": [
      "Kuse",
      "Shiwalaya",
      "Barekot",
      "Junichande",
      "Nalagad",
      "Bheri",
      "Chhedagad "
    ],
    "RUKUM WEST": [
      "Tribeni",
      "Sani Bheri",
      "Banfikot",
      "Aathbiskot",
      "Chaurjahari",
      "Musikot "
    ],
    "SALYAN": [
      "Kumakh",
      "Darma",
      "Kapurkot",
      "Kalimati",
      "Tribeni",
      "Chhatreshwori",
      "Siddha Kumakh",
      "Sharada",
      "Bangad Kupinde",
      "Bagchaur "
    ],
    "SURKHET": [
      "Chaukune",
      "Simta",
      "Chingad",
      "Barahtal",
      "Gurbhakot",
      "Panchpuri",
      "Bheriganga",
      "Lekbeshi",
      "Birendranagar "
    ],
    "BAJURA": [
      "Gaumul",
      "Himali",
      "Jagannath",
      "Khaptad Chhededaha",
      "Swami Kartik Khaapar",
      "Badimalika",
      "Tribeni",
      "Budhiganga",
      "Budhinanda "
    ],
    "BAJHANG": [
      "Masta",
      "Thalara",
      "Talkot",
      "Surma",
      "SaiPaal",
      "Durgathali",
      "Bithadchir",
      "Kedarseu",
      "Khaptadchhanna",
      "Chabispathivera",
      "JayaPrithivi",
      "Bungal "
    ],
    "DARCHULA": [
      "Lekam",
      "Naugad",
      "Byas",
      "Dunhu",
      "Marma",
      "Apihimal",
      "Malikaarjun",
      "Mahakali",
      "Shailyashikhar "
    ],
    "BAITADI": [
      "Sigas",
      "Shivanath",
      "Surnaya",
      "Dilasaini",
      "Pancheshwar",
      "Dogadakedar",
      "Melauli",
      "Dasharathchanda",
      "Purchaudi",
      "Patan "
    ],
    "DADELDHURA": [
      "Alital",
      "Ajaymeru",
      "Bhageshwar",
      "Nawadurga",
      "Ganayapdhura",
      "Amargadhi",
      "Parashuram "
    ],
    "DOTI": [
      "Sayal",
      "Adharsha",
      "Jorayal",
      "Badikedar",
      "Purbichauki",
      "K I Singh",
      "Bogtan Foodsil",
      "Dipayal Silgadi",
      "Shikhar "
    ],
    "ACHHAM": [
      "Dhakari",
      "Mellekh",
      "Chaurpati",
      "Ramaroshan",
      "Turmakhad",
      "Bannigadhi Jayagadh",
      "Sanphebagar",
      "Mangalsen",
      "Kamalbazar",
      "Panchadewal Binayak "
    ],
    "KAILALI": [
      "Chure",
      "Janaki",
      "Kailari",
      "Joshipur",
      "Mohanyal",
      "Bardagoriya",
      "Tikapur",
      "Ghodaghodi",
      "Bhajani",
      "Dhangadhi",
      "Gauriganga",
      "Godawari",
      "Lamkichuha "
    ],
    "KANCHANPUR": [
      "Beldandi",
      "Laljhadi",
      "Punarbas",
      "Krishnapur",
      "Mahakali",
      "Bedkot",
      "Belauri",
      "Bhimdatta",
      "Shuklaphanta "
    ]
  };

  List<String> getMunicipalities(String district) {
    List<String> municipalities =
        _districtsAndMunicipalities[district.toUpperCase()];
    municipalities.sort();
    return municipalities;
  }
}
